param(
    [string]
    $ResourceGroupName,
    [parameter(Mandatory=$true)]
    [String[]]
    $environment,
    [parameter(Mandatory=$true)]
    [String[]]
    $application,
    [parameter(Mandatory=$true)]
    [String[]]
    $region,
    [parameter(Mandatory=$true)]
    [String[]]
    $applicationName,
    [parameter(Mandatory=$true)]
    [String[]]
    $applicationOwner,
    [parameter(Mandatory=$true)]
    [String[]]
    $applicationDeveloper,
    [parameter(Mandatory=$true)]
    [String[]]
    $applicationID,
    [parameter(Mandatory=$true)]
    [String[]]
    $applicationDescription,
    [parameter(Mandatory=$true)]
    [String[]]
    $businessOwner,
    [parameter(Mandatory=$true)]
    [String[]]
    $costCenter,
    [parameter(Mandatory=$true)]
    [String[]]
    $departmentOrBrand,
    [parameter(Mandatory=$true)]
    [String[]]
    $environmentTag,
    [parameter(Mandatory=$true)]
    [String[]]
    $projectID,
    [parameter(Mandatory=$true)]
    [String[]]
    $primaryFunction,
    [parameter(Mandatory=$true)]
    [String[]]
    $installDate,
    [parameter(Mandatory=$true)]
    [String[]]
    $fiscalYear
)
$Tags = @{ 
           environment="$environment"; 
           application="$application";
           region="$region"; 
           applicationName="$applicationName";
           applicationOwner="$applicationOwner" 
           applicationDeveloper="$applicationDeveloper"; 
           applicationID="$applicationID"; 
           applicationDescription="$applicationDescription"; 
           businessOwner="$businessOwner"; 
           costCenter="$costCenter"; 
           departmentOrBrand="$departmentOrBrand"; 
           projectID="$projectID"; 
           primaryFunction="$primaryFunction"; 
           installDate="$installDate";
           fiscalYear="$fiscalYear";
           }
$resources = Get-AzureRmResource -ResourceGroupName $ResourceGroupName
foreach ($resource in $resources)
{
   Set-AzureRmResource -Tag $Tags -ResourceId $resource.ResourceId -Force
}

#.\Update-ResourceTags.ps1 -ResourceGroupName $resourceGroupName -environment $environment -application $application -region $region -applicationName $applicationName -applicationOwner $applicationOwner -applicationDeveloper $applicationDeveloper -applicationID $applicationID -applicationDescription $applicationDescription -businessOwner $businessOwner -costCenter $costCenter -departmentOrBrand $departmentOrBrand -environmentTag $environmentTag -projectID $projectID -primaryFunction $primaryFunction -installDate $installDate -fiscalYear $fiscalyear