<#
.SYNOPSIS
    Deploys a diagnostic storage account for platform diagnostics and boot diagnostics.

.DESCRIPTION
    This script deploys an Azure Storage Account dedicated to storing diagnostic data
    for the platform. The storage account is used for:
    
    - VM boot diagnostics (serial console output and screenshots)
    - Platform diagnostic logs and metrics
    - Troubleshooting data for Azure resources
    - Compliance and audit log retention
    
    The storage account provides:
    - Centralized diagnostic data collection
    - Long-term retention of troubleshooting data
    - Support for VM boot diagnostics across the platform
    - Foundation for diagnostic data analysis
    
    A random string is appended to the deployment name to ensure uniqueness.

.PARAMETER diagStorageLocation
    The Azure region where the storage account will be deployed.
    Should match the region of the resources being monitored.
    Example: 'eastus', 'westus2'

.PARAMETER resourceGroup
    The resource group where the storage account will be deployed.
    Example: 'rg-platform-prod'

.EXAMPLE
    .\ta-platform-diagnosticsstorage.ps1 -diagStorageLocation 'eastus' -resourceGroup 'rg-platform-prod'

.NOTES
    Author: Jason Rinehart aka Technical Anxiety
    Blog: https://technicalanxiety.com
    Last Updated: 2025-01-15
    
    Prerequisites:
    - Resource group must exist
    - User must have Contributor role on the resource group
    - ARM template file must exist: ./templates/platform/diagstorage.json
    
    Storage Account Configuration:
    - The storage account name is generated by the ARM template
    - Standard storage tier is typically used
    - Lifecycle management policies can be configured post-deployment
    
    Post-Deployment:
    - Configure VMs to use this storage account for boot diagnostics
    - Set up diagnostic settings for Azure resources
    - Consider implementing lifecycle management for cost optimization
    
    Impact: Provides centralized diagnostic storage for the entire platform.

.VERSION
    2.0.0 - Enhanced documentation

.CHANGELOG
    2.0.0 - 2025-01-15 - Enhanced documentation and parameter validation
    1.0.0 - Initial version
#>

param (
    [Parameter(Mandatory=$true, HelpMessage="Azure region for the storage account")]
    [ValidateNotNullOrEmpty()]
    [string]$diagStorageLocation,

    [Parameter(Mandatory=$true, HelpMessage="Resource group for deployment")]
    [ValidateNotNullOrEmpty()]
    [string]$resourceGroup
)

# Generate a random string for unique deployment naming
# This ensures multiple deployments don't conflict
$randStr = -join ((65..90) + (97..122) | Get-Random -Count 8 | % {[char]$_})

# Output deployment information
Write-Output "=========================================="
Write-Output "Deploy Diagnostic Storage Account"
Write-Output "=========================================="
Write-Output "Resource Group: $resourceGroup"
Write-Output "Location: $diagStorageLocation"
Write-Output "Deployment Name: deploy-diagnostic-storage-${randStr}"
Write-Output ""

Try {
    # Deploy the diagnostic storage account
    # This storage account will be used for VM boot diagnostics and platform logs
    New-AzResourceGroupDeployment `
        -Name "deploy-diagnostic-storage-${randStr}" `
        -TemplateFile ./templates/platform/diagstorage.json `
        -ResourceGroupName $resourceGroup `
        -diagStorageLocation $diagStorageLocation `
        -ErrorAction Stop
    
    Write-Output "✓ Diagnostic storage account deployed successfully"
}
Catch {
    Write-Error "Failed to deploy diagnostic storage account: $_"
    throw
}

Write-Output ""
Write-Output "=========================================="
Write-Output "Deployment Complete"
Write-Output "=========================================="